name: run tests

on: [push, pull_request]


jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: generate version
        run: |-
          echo -n "v0.0.1" > version.txt
      - name: Test
        run: go test -v .